# Generated by Django 4.2.1 on 2023-05-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
        migrations.RenameModel(
            old_name='Discplinas',
            new_name='Discplina',
        ),
    ]
